(function(){var aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},m=ba(this),q=function(a,b){if(b)a:{var c=m;a=a.split(".");for(var e=0;e<a.length-
1;e++){var g=a[e];if(!(g in c))break a;c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}},ca=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},r=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ca(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},da=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);
return c},v=function(a){return u(a,a)},u=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a},w=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};q("globalThis",function(a){return a||m});
q("Symbol",function(a){if(a)return a;var b=function(k,d){this.g=k;aa(this,"description",{configurable:!0,writable:!0,value:d})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0,g=function(k){if(this instanceof g)throw new TypeError("Symbol is not a constructor");return new b(c+(k||"")+"_"+e++,k)};return g});
q("Promise",function(a){function b(){this.g=null}function c(d){return d instanceof g?d:new g(function(f){f(d)})}if(a)return a;b.prototype.h=function(d){if(this.g==null){this.g=[];var f=this;this.i(function(){f.l()})}this.g.push(d)};var e=m.setTimeout;b.prototype.i=function(d){e(d,0)};b.prototype.l=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var f=0;f<d.length;++f){var h=d[f];d[f]=null;try{h()}catch(l){this.j(l)}}}this.g=null};b.prototype.j=function(d){this.i(function(){throw d;
})};var g=function(d){this.g=0;this.i=void 0;this.h=[];this.o=!1;var f=this.j();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}};g.prototype.j=function(){function d(l){return function(n){h||(h=!0,l.call(f,n))}}var f=this,h=!1;return{resolve:d(this.D),reject:d(this.l)}};g.prototype.D=function(d){if(d===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof g)this.G(d);else{a:switch(typeof d){case "object":var f=d!=null;break a;case "function":f=!0;break a;default:f=!1}f?
this.C(d):this.m(d)}};g.prototype.C=function(d){var f=void 0;try{f=d.then}catch(h){this.l(h);return}typeof f=="function"?this.H(f,d):this.m(d)};g.prototype.l=function(d){this.v(2,d)};g.prototype.m=function(d){this.v(1,d)};g.prototype.v=function(d,f){if(this.g!=0)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.g);this.g=d;this.i=f;this.g===2&&this.F();this.B()};g.prototype.F=function(){var d=this;e(function(){if(d.A()){var f=m.console;typeof f!=="undefined"&&f.error(d.i)}},
1)};g.prototype.A=function(){if(this.o)return!1;var d=m.CustomEvent,f=m.Event,h=m.dispatchEvent;if(typeof h==="undefined")return!0;typeof d==="function"?d=new d("unhandledrejection",{cancelable:!0}):typeof f==="function"?d=new f("unhandledrejection",{cancelable:!0}):(d=m.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.i;return h(d)};g.prototype.B=function(){if(this.h!=null){for(var d=0;d<this.h.length;++d)k.h(this.h[d]);this.h=null}};
var k=new b;g.prototype.G=function(d){var f=this.j();d.u(f.resolve,f.reject)};g.prototype.H=function(d,f){var h=this.j();try{d.call(f,h.resolve,h.reject)}catch(l){h.reject(l)}};g.prototype.then=function(d,f){function h(p,t){return typeof p=="function"?function(H){try{l(p(H))}catch(I){n(I)}}:t}var l,n,J=new g(function(p,t){l=p;n=t});this.u(h(d,l),h(f,n));return J};g.prototype.catch=function(d){return this.then(void 0,d)};g.prototype.u=function(d,f){function h(){switch(l.g){case 1:d(l.i);break;case 2:f(l.i);
break;default:throw Error("Unexpected state: "+l.g);}}var l=this;this.h==null?k.h(h):this.h.push(h);this.o=!0};g.resolve=c;g.reject=function(d){return new g(function(f,h){h(d)})};g.race=function(d){return new g(function(f,h){for(var l=r(d),n=l.next();!n.done;n=l.next())c(n.value).u(f,h)})};g.all=function(d){var f=r(d),h=f.next();return h.done?c([]):new g(function(l,n){function J(H){return function(I){p[H]=I;t--;t==0&&l(p)}}var p=[],t=0;do p.push(void 0),t++,c(h.value).u(J(p.length-1),n),h=f.next();
while(!h.done)})};return g});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var x=this||self,ea=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var e=c.slice();e.push.apply(e,arguments);return a.apply(this,e)}},y=function(a,b){function c(){}c.prototype=b.prototype;a.J=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.I=function(e,g,k){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];return b.prototype[g].apply(e,d)}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var fa={};function ha(){if(fa!==fa)throw Error("Bad secret");};var ia=globalThis.trustedTypes,z;function ja(){var a=null;if(!ia)return a;try{var b=function(c){return c};a=ia.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){throw c;}return a};var A=function(a){ha();this.g=a};A.prototype.toString=function(){return this.g+""};function B(a){var b;z===void 0&&(z=ja());a=(b=z)?b.createScriptURL(a):a;return new A(a)};var C=function(a){ha();this.g=a};C.prototype.toString=function(){return this.g};new C("about:blank");new C("about:invalid#zClosurez");function D(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,D);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}y(D,Error);D.prototype.name="CustomError";function E(a,b){a=a.split("%s");for(var c="",e=a.length-1,g=0;g<e;g++)c+=a[g]+(g<b.length?b[g]:"%s");D.call(this,c+a[e])}y(E,D);E.prototype.name="AssertionError";function F(a,b,c,e){var g="Assertion failed";if(c){g+=": "+c;var k=e}else a&&(g+=": "+a,k=b);throw new E(""+g,k||[]);}
var G=function(a,b,c){a||F("",null,b,Array.prototype.slice.call(arguments,2))},ka=function(a,b,c){a==null&&F("Expected to exist: %s.",[a],b,Array.prototype.slice.call(arguments,2));return a},K=function(a,b,c){if(typeof a!=="function"){var e=typeof a;F("Expected function but got %s: %s.",[e!="object"?e:a?Array.isArray(a)?"array":e:"null",a],b,Array.prototype.slice.call(arguments,2))}};var la=v([""]),ma=u(["\x00"],["\\0"]),na=u(["\n"],["\\n"]),oa=u(["\x00"],["\\u0000"]),pa=v([""]),qa=u(["\x00"],["\\0"]),ra=u(["\n"],["\\n"]),sa=u(["\x00"],["\\u0000"]);function L(a){return Object.isFrozen(a)&&Object.isFrozen(a.raw)}function M(a){return a.toString().indexOf("`")===-1}var ta=M(function(a){return a(la)})||M(function(a){return a(ma)})||M(function(a){return a(na)})||M(function(a){return a(oa)}),ua=L(pa)&&L(qa)&&L(ra)&&L(sa);var va=[],wa=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};va.indexOf(wa)===-1&&va.push(wa);function xa(a,b){if(b instanceof A)b=b.g;else throw Error("Unexpected type when unwrapping TrustedResourceUrl");a.src=b;var c;b=a.ownerDocument;b=b===void 0?document:b;var e;b=(e=(c=b).querySelector)==null?void 0:e.call(c,"script[nonce]");(c=b==null?"":b.nonce||b.getAttribute("nonce")||"")&&a.setAttribute("nonce",c)};var ya=function(){var a=document;var b="SCRIPT";a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)};var za=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};var N=function(a,b){this.i=a;this.j=b;this.h=0;this.g=null};N.prototype.get=function(){if(this.h>0){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};var Aa=function(a,b){a.j(b);a.h<100&&(a.h++,b.next=a.g,a.g=b)};function Ba(a){x.setTimeout(function(){throw a;},0)};var Ca=function(){this.h=this.g=null};Ca.prototype.add=function(a,b){var c=Da.get();c.set(a,b);this.h?this.h.next=c:(G(!this.g),this.g=c);this.h=c};var Fa=function(){var a=Ea,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b},Da=new N(function(){return new O},function(a){return a.reset()}),O=function(){this.next=this.g=this.h=null};O.prototype.set=function(a,b){this.h=a;this.g=b;this.next=null};O.prototype.reset=function(){this.next=this.g=this.h=null};var P=x.console&&x.console.createTask?x.console.createTask.bind(x.console):void 0,Q=P?Symbol("consoleTask"):void 0;
function R(a,b){function c(){var f=w.apply(0,arguments),h=this;return d.run(function(){return a.call.apply(a,[h].concat(f instanceof Array?f:da(r(f))))})}b=b===void 0?"anonymous":b;if(Q&&a[Q])return a;var e=a,g,k=(g=Ga)==null?void 0:g();a=function(){var f=w.apply(0,arguments),h,l=(h=Ga)==null?void 0:h();if(k!==l)throw Error(b+" was scheduled in '"+k+"' but called in '"+l+"'.\nMake sure your test awaits all async calls.\n\nTIP: To help investigate, debug the test in Chrome and look at the async portion\nof the call stack to see what originally scheduled the callback.  Then, make the\ntest wait for the relevant asynchronous work to finish.");return e.call.apply(e,
[this].concat(f instanceof Array?f:da(r(f))))};if(!P)return a;var d=P(a.name||b);c[ka(Q)]=d;return c}var Ga;var S,T=!1,Ea=new Ca,U=function(a,b){a=R(a,"goog.async.run");S||Ha();T||(S(),T=!0);Ea.add(a,b)},Ha=function(){var a=Promise.resolve(void 0);S=function(){a.then(Ia)}};function Ia(){for(var a;a=Fa();){try{a.h.call(a.g)}catch(b){Ba(b)}Aa(Da,a)}T=!1};var V=function(){};var Y=function(a){this.g=0;this.o=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(a!=V)try{var b=this;a.call(void 0,function(c){W(b,2,c)},function(c){if(!(c instanceof X))try{if(c instanceof Error)throw c;throw Error("Promise rejected.");}catch(e){}W(b,3,c)})}catch(c){W(this,3,c)}},Ja=function(){this.next=this.j=this.i=this.h=this.g=null;this.l=!1};Ja.prototype.reset=function(){this.j=this.i=this.h=this.g=null;this.l=!1};
var Ka=new N(function(){return new Ja},function(a){a.reset()}),La=function(a,b,c){var e=Ka.get();e.h=a;e.i=b;e.j=c;return e},Ma=function(a){if(a instanceof Y)return a;var b=new Y(V);W(b,2,a);return b};Y.prototype.then=function(a,b,c){a!=null&&K(a,"opt_onFulfilled should be a function.");b!=null&&K(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return Na(this,za(typeof a==="function"?a:null),za(typeof b==="function"?b:null),c)};
Y.prototype.$goog_Thenable=!0;Y.prototype.cancel=function(a){if(this.g==0){var b=new X(a);U(function(){Oa(this,b)},this)}};
var Oa=function(a,b){if(a.g==0)if(a.i){var c=a.i;if(c.h){for(var e=0,g=null,k=null,d=c.h;d&&(d.l||(e++,d.g==a&&(g=d),!(g&&e>1)));d=d.next)g||(k=d);g&&(c.g==0&&e==1?Oa(c,b):(k?(e=k,G(c.h),G(e!=null),e.next==c.j&&(c.j=e),e.next=e.next.next):Pa(c),Qa(c,g,3,b)))}a.i=null}else W(a,3,b)},Sa=function(a,b){a.h||a.g!=2&&a.g!=3||Ra(a);G(b.h!=null);a.j?a.j.next=b:a.h=b;a.j=b},Na=function(a,b,c,e){b&&(b=R(b,"goog.Promise.then"));c&&(c=R(c,"goog.Promise.then"));var g=La(null,null,null);g.g=new Y(function(k,d){g.h=
b?function(f){try{var h=b.call(e,f);k(h)}catch(l){d(l)}}:k;g.i=c?function(f){try{var h=c.call(e,f);h===void 0&&f instanceof X?d(f):k(h)}catch(l){d(l)}}:d});g.g.i=a;Sa(a,g);return g.g};Y.prototype.B=function(a){G(this.g==1);this.g=0;W(this,2,a)};Y.prototype.A=function(a){G(this.g==1);this.g=0;W(this,3,a)};
var W=function(a,b,c){if(a.g==0){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.g=1;a:{var e=c,g=a.B,k=a.A;if(e instanceof Y){g!=null&&K(g,"opt_onFulfilled should be a function.");k!=null&&K(k,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");Sa(e,La(g||V,k||null,a));var d=!0}else{if(e)try{var f=!!e.$goog_Thenable}catch(l){f=!1}else f=!1;if(f)e.then(g,k,a),d=!0;else{f=typeof e;if(f=="object"&&e!=null||f=="function")try{var h=
e.then;if(typeof h==="function"){Ta(e,h,g,k,a);d=!0;break a}}catch(l){k.call(a,l);d=!0;break a}d=!1}}}d||(a.o=c,a.g=b,a.i=null,Ra(a),b!=3||c instanceof X||Ua(a,c))}},Ta=function(a,b,c,e,g){var k=!1,d=function(h){k||(k=!0,c.call(g,h))},f=function(h){k||(k=!0,e.call(g,h))};try{b.call(a,d,f)}catch(h){f(h)}},Ra=function(a){a.m||(a.m=!0,U(a.v,a))},Pa=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);b!=null&&G(b.h!=null);return b};
Y.prototype.v=function(){for(var a;a=Pa(this);)Qa(this,a,this.g,this.o);this.m=!1};var Qa=function(a,b,c,e){if(c==3&&b.i&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,Va(b,c,e);else try{b.l?b.h.call(b.j):Va(b,c,e)}catch(g){Wa.call(null,g)}Aa(Ka,b)},Va=function(a,b,c){b==2?a.h.call(a.j,c):a.i&&a.i.call(a.j,c)},Ua=function(a,b){a.l=!0;U(function(){a.l&&Wa.call(null,b)})},Wa=Ba,X=function(a){D.call(this,a)};y(X,D);X.prototype.name="cancel";var Xa,Ya;Ya=B("https://apis.google.com/js/api.js");function Za(){return $a().then(function(a){return new Y(function(b,c){a.load("client",{callback:ea(b,a),timeout:1E4,ontimeout:function(){c(Error("Timeout loading the requested gapi library: client"))}})})})}
function $a(){var a=window;return a.gapi?Ma(a.gapi):Xa?Xa:Xa=new Y(function(b,c){var e=ya();xa(e,Ya);e.onload=function(){b(a.gapi)};e.onerror=function(){c(Error("Failed to load gapi."))};document.getElementsByTagName("head")[0].appendChild(e)})};var ab=v(["https://accounts.google.com/gsi/client"]);function bb(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");cb?(db=!0,eb&&Z()):Z()}
var Z,fb=null,gb=window,cb=!(gb.colabExperiments&&gb.colabExperiments.first_party_auth),eb=!1,db=!1,hb=document.getElementsByTagName("script")[0],ib=function(a){var b=w.apply(1,arguments);if(!Array.isArray(a)||!Array.isArray(a.raw)||a.length!==a.raw.length||!ta&&a===a.raw||!(ta&&!ua||L(a))||b.length+1!==a.length)throw new TypeError("\n    ############################## ERROR ##############################\n\n    It looks like you are trying to call a template tag function (fn`...`)\n    using the normal function syntax (fn(...)), which is not supported.\n\n    The functions in the safevalues library are not designed to be called\n    like normal functions, and doing so invalidates the security guarantees\n    that safevalues provides.\n\n    If you are stuck and not sure how to proceed, please reach out to us\n    instead through:\n     - go/ise-hardening-yaqs (preferred) // LINE-INTERNAL\n     - g/ise-hardening // LINE-INTERNAL\n     - https://github.com/google/safevalues/issues\n\n    ############################## ERROR ##############################");
if(b.length===0)return B(a[0]);var c=a[0].toLowerCase();if(/^data:/.test(c))throw Error("Data URLs cannot have expressions in the template literal input.");if(/^https:\/\//.test(c)||/^\/\//.test(c)){var e=c.indexOf("//")+2;var g=c.indexOf("/",e);if(g<=e)throw Error("Can't interpolate data in a url's origin, Please make sure to fully specify the origin, terminated with '/'.");e=c.substring(e,g);if(!/^[0-9a-z.:-]+$/i.test(e))throw Error("The origin contains unsupported characters.");if(!/^[^:]*(:[0-9]+)?$/i.test(e))throw Error("Invalid port number.");
if(!/(^|\.)[a-z][^.]*$/i.test(e))throw Error("The top-level domain must start with a letter.");e=!0}else e=!1;if(!e)if(/^\//.test(c))if(c==="/"||c.length>1&&c[1]!=="/"&&c[1]!=="\\")e=!0;else throw Error("The path start in the url is invalid.");else e=!1;if(!(e=e||RegExp("^[^:\\s\\\\/]+/").test(c)))if(/^about:blank/.test(c)){if(c!=="about:blank"&&!/^about:blank#/.test(c))throw Error("The about url is invalid.");e=!0}else e=!1;if(!e)throw Error("Trying to interpolate expressions in an unsupported url format.");
c=a[0];for(e=0;e<b.length;e++)c+=encodeURIComponent(b[e])+a[e+1];return B(c)}(ab);function jb(){if(fb)return fb;window.performance.mark("gapi_load_start");return fb=new Promise(function(a,b){Z=a;cb&&kb(function(){b(Error("Error loading "+ib))});Za().then(bb,function(c){b(Error("Error loading gapi client library: "+c))})})}function kb(a){lb({src:ib,onload:function(){eb=!0;db&&Z()},onerror:a})}
function lb(a){var b=ya();xa(b,a.src);b.async=!0;a.onload&&(b.onload=a.onload);a.onerror&&(b.onerror=a.onerror);hb.parentNode.insertBefore(b,hb)}gb.colab_gapi_loader={load:jb};jb().then(function(){},function(){});}).call(this);
